[package]
name = "consumer"
version.workspace = true
edition.workspace = true

[dependencies]
rdkafka = { workspace = true, features = ["cmake-build"] }
tokio = { workspace = true, features = ["full"] }
