[package]
name = "mybank"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.83"
cqrs-es = "0.4.12"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
